[dependencies.wasm-project]
default-features = false
features = []
package = 'unit-network-runtime'
path = '/root/Unit-Network/runtime'

[lib]
crate-type = ['cdylib']
name = 'unit_network_runtime'

[package]
edition = '2018'
name = 'unit-network-runtime-wasm'
version = '1.0.0'
[profile.dev]
panic = 'abort'

[profile.release]
lto = true
panic = 'abort'

[workspace]
